# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - streamlit-ui

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_c600ea10b2bc4fa99444983e3bae1236 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_3b2a3de925c54c4b86e58585ae6c5bae }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_c600ea10b2bc4fa99444983e3bae1236 }}/bigzz22/streamlit-ui:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'streamlit-ui'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_77fc2a330b51442a90000761d6396d27 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_c600ea10b2bc4fa99444983e3bae1236 }}/bigzz22/streamlit-ui:${{ github.sha }}'